### ISSUE TITLE
spark3: cannot start history server

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/spark-old#1]
On version `3.2.2-TDP-0.1.0-SNAPSHOT`, the History Server fails to start with the following error:
```
ERROR history.HistoryServer: Failed to bind HistoryServer
java.lang.IllegalStateException: class org.apache.hadoop.security.authentication.server.AuthenticationFilter is not a javax.servlet.Filter
        at org.sparkproject.jetty.servlet.FilterHolder.doStart(FilterHolder.java:103)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.sparkproject.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:730)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.sparkproject.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
        at org.sparkproject.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
        at org.sparkproject.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
        at org.sparkproject.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.apache.spark.ui.ServerInfo.addHandler(JettyUtils.scala:491)
        at org.apache.spark.ui.WebUI.$anonfun$bind$3(WebUI.scala:148)
        at org.apache.spark.ui.WebUI.$anonfun$bind$3$adapted(WebUI.scala:148)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.ui.WebUI.bind(WebUI.scala:148)
        at org.apache.spark.deploy.history.HistoryServer.bind(HistoryServer.scala:164)
        at org.apache.spark.deploy.history.HistoryServer$.main(HistoryServer.scala:310)
        at org.apache.spark.deploy.history.HistoryServer.main(HistoryServer.scala)
```
This issue appears to be linked to [SPARK-35959](https://issues.apache.org/jira/browse/SPARK-35959):
> Currently Spark uses Hadoop shaded client by default. However, if Spark users want to build Spark with older version of Hadoop, such as 3.1.x, the shaded client cannot be used (currently it only support Hadoop 3.2.2+ and 3.3.1+).

**Comment by Nuttymoon** [comment]
Fixed in https://github.com/TOSIT-IO/spark/commit/89acb0c37023828aac04a99cce5a5ddc2aafbfe8

Took inspiration from https://github.com/apache/spark/pull/33160
